### ISSUE TITLE
Clients fail to connect to streaming server

### ISSUE THREAD

**Issue by sebrk** [aws-samples/deploying-unreal-engine-pixel-streaming-server-on-ec2#1]
This issue seems to be all over the internet in regards to Unreal Pixel Streaming. It might not be associated with AWS per se but it is still an issue that is affecting the end result that this repo is trying to do.

The issue is that clients are not able to connect properly. Users are greeted with the "Click to start" page. Clicking this updates the page with a few controls and the text "Starting connection to server, please wait...". From this point on nothing more will happen.

I believe this to be a networking issue with the TURN server but still have to dig for more information.

Also note that I have tried to connect from multiple machines directly connected to the internet. Any ideas would be great.

**Comment by yardenshoham** [comment]
It happened to me as well
![image](https://user-images.githubusercontent.com/20454870/105221198-72264c80-5b61-11eb-9bae-001ee51c4c81.png)
![image](https://user-images.githubusercontent.com/20454870/105221217-7bafb480-5b61-11eb-8c69-002f8698bad3.png)

**Comment by yardenshoham** [comment]
I looked at the logs, I saw this:
`A D3D11-compatible GPU (Feature Level 11.0, Shader Model 5.0) is required to run the engine.`

I think the default instance doesn't have a compatible GPU. I don't know how to proceed.
![image](https://user-images.githubusercontent.com/20454870/105231959-5aa29000-5b70-11eb-8c73-ad030f72b38c.png)

@kashman-amzn can you advise?

**Comment by kashman-amzn** [comment]
Thank you for tagging me with this issue. I wanted to first check that an important step was done to the UE4 build to correctly attach the Stun/Turn servers to the public IP address and not the AWS internal IP address. The step is to modify a specific file in your build, described in "Step 2. Create UE4 Pixel Streaming Build", and specifically the 3rd item. I have a screenshot for your reference as well.

![FileModification](https://user-images.githubusercontent.com/69484862/105233597-eb508000-5b1e-11eb-8c21-31d1132adf2b.png)

In regards to verifying the build can run on the instance, you can remote into the machine using NICE DCV to debug. You can connect and try to access the Pixel Stream via localhost, and you can also put a standard Windows build on the machine to test.

Please share your results here. Thanks!

**Comment by yardenshoham** [comment]
The build is not even running. It can't start and fails with `A D3D11-compatible GPU (Feature Level 11.0, Shader Model 5.0) is required to run the engine.`

I didn't execute the step you mentioned because I'm using UE 4.26.

**Comment by sebrk** [comment]
My issue was resolved specifying the streaming IP in a shortcut to the UE4 EXE. It seems you are having different issues that warrants its own issue. I will add the command here later today and close the issue.

**Comment by sebrk** [comment]
Here you go:

`PixelStreamingIP=<PUBLIC IP>`

Related documentation: https://docs.unrealengine.com/en-US/SharingAndReleasing/PixelStreaming/PixelStreamingIntro/index.html

**Comment by yardenshoham** [comment]
Continued in #2

**Comment by RamGowthamTF** [comment]
facing same issue, but installing RTX drivers on Tesla T4 is how compatible?
