### ISSUE TITLE
Pixel Streaming Crashing in Edge and Chrome 89

### ISSUE THREAD

**Issue by Kemerd** [aws-samples/deploying-unreal-engine-pixel-streaming-server-on-ec2#6]
Just writing an update to this repo. Please see Post #6 at https://forums.unrealengine.com/unreal-engine/feedback-for-epic/1869186-pixel-streaming-not-working-in-chrome-version-89-ue4-will-crash-when-i-access-signallingwebserver

For the fix.

"This is happening due to the recent change in Chrome M89 to use the extmaps-allow-mixed SDP attribute by default."

Thought I might make a request here so it can be updated for others.

**Comment by CreatoonAuraML** [comment]
@Kemerd Hey this link is not working, do you have some other way to access it, Thanks
